[
 {
  id: 1,
  name: '',
  type: 'sneakers',
  image: 'https://robohash.org/eosminusvoluptates.jpg?size=50x50&set=set1',
  price: '£4119.32',
  reviews: 1000,
 },

 {
  id: 2,
  name: '',
  type: 'boots',
  image: 'https://robohash.org/quasiomnisipsum.jpg?size=50x50&set=set1',
  price: '£4874.39',
 },

 {
  id: 3,
  name: '',
  type: 'sneakers',
  image: 'https://robohash.org/consequunturametmodi.jpg?size=500x200&set=set1',
  price: '£4934.75',
 },

 {
  id: 4,
  name: '',
  type: 'sneakers',
  image: 'https://robohash.org/solutamaximeunde.jpg?size=50x50&set=set1',
  price: '£4594.76',
 },
 {
  id: 5,
  name: '',
  type: 'sandals',
  image: 'https://robohash.org/magninobisvero.jpg?size=50x50&set=set1',
  price: '£2244.83',
 },
 {
  id: 6,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/isteofficiadeserunt.jpg?size=50x50&set=set1',
  price: '£4306.96',
 },
 {
  id: 7,
  name: '',
  type: 'sneakers',
  image: 'https://robohash.org/delenitiestnesciunt.jpg?size=50x50&set=set1',
  price: '£4397.84',
 },
 {
  id: 8,
  name: '',
  type: 'sandals',
  image: 'https://robohash.org/doloremoptiorepellendus.jpg?size=50x50&set=set',
  price: '£2780.18',
 },
 {
  id: 9,
  name: '',
  type: 'boots',
  image: 'https://robohash.org/nequenihilconsectetur.jpg?size=50x50&set=set1',
  price: '£2322.47',
 },
 {
  id: 10,
  name: '',
  type: 'sneakers',
  image:
   'https://robohash.org/repellendusnihilvoluptatem.jpg?size=50x50&set=set1',
  price: '£2455.35',
 },
 {
  id: 11,
  name: '',
  type: 'heels',
  image: 'https://robohash.org/veniamquamsunt.jpg?size=50x50&set=set1',
  price: '£4432.00',
 },
 {
  id: 12,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/etrationeconsequuntur.jpg?size=50x50&set=set1',
  price: '£4411.33',
 },
 {
  id: 13,
  name: '',
  type: 'heels',
  image: 'https://robohash.org/odioetperspiciatis.jpg?size=50x50&set=set1',
  price: '£2413.03',
 },
 {
  id: 14,
  name: '',
  type: 'sneakers',
  image: 'https://robohash.org/solutavoluptasminima.jpg?size=50x50&set=set1',
  price: '£3218.45',
 },
 {
  id: 15,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/nihilnontotam.jpg?size=50x50&set=set1',
  price: '£2380.44',
 },
 {
  id: 16,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/ipsumsititaque.jpg?size=50x50&set=set1',
  price: '£4830.06',
 },
 {
  id: 17,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/nullarerumperspiciatis.jpg?size=50x50&set=set1',
  price: '£4852.97',
 },
 {
  id: 18,
  name: '',
  type: 'heels',
  image: 'https://robohash.org/placeatutdistinctio.jpg?size=50x50&set=set1',
  price: '£3256.61',
 },
 {
  id: 19,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/officiaautemdebitis.jpg?size=50x50&set=set1',
  price: '£3916.06',
 },
 {
  id: 20,
  name: '',
  type: 'loafers',
  image: 'https://robohash.org/quodmollitiasint.jpg?size=50x50&set=set1',
  price: '£3769.03',
 },
];
